[package]
name = "bmark"
version = "0.1.0"
edition = "2021"
description = "Bookmarks cli for your local file system."
readme = "README.md"
documentation = "https://github.com/BalderHolst/bmark" # TODO
homepage = "https://github.com/BalderHolst/bmark" # TODO
repository = "https://github.com/BalderHolst/bmark"
license = "MIT"
license-file = "LICENSE"
keywords = ["bookmarks", "cli", "local", "terminal", "dmenu"]
categories = ["command-line-utilities"]

[dependencies]
serde = { version = "1.0.159", features = ["derive"] } 
toml = "0.7.3"
